name: README to HTML

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'README.md'

jobs:
  convert-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install pandoc
      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      # Convert README.md to HTML
      - name: Convert README.md to HTML
        run: pandoc README.md -o README.html

      # Create or update index.html with the contents of README.html
      - name: Create or update index.html
        run: |
          echo "<html><head><title>README</title></head><body>" > index.html
          cat README.html >> index.html
          echo "</body></html>" >> index.html

      # Optionally, upload the HTML files as artifacts
      - name: Upload HTML files
        uses: actions/upload-artifact@v3
        with:
          name: HTML-files
          path: |
            README.html
            index.html
