name: README to HTML

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'README.md'

jobs:
  convert-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install pandoc
      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      # Convert README.md to README.html
      - name: Convert README.md to README.html
        run: pandoc README.md -o README.html

      # Create index.html and embed README.html inside it
      - name: Create index.html
        run: |
          echo "<html><head><title>README</title></head><body>" > index.html
          if [ -f README.html ]; then
            cat README.html >> index.html
          else
            echo "<p>Error: README.html not found</p>" >> index.html
          fi
          echo "</body></html>" >> index.html

      # Configure Git for commit and push
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Commit and push the changes
      - name: Commit and push changes
        run: |
          git add README.html index.html
          git commit -m "Automated update: Converted README.md to index.html"
          git push origin main
