name: README to HTML

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'README.md'

jobs:
  convert-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install pandoc
      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      # Convert README.md to README.html
      - name: Convert README.md to README.html
        run: pandoc README.md -o README.html

      # Create index.html and embed README.html inside it
      - name: Create index.html
        run: |
          echo "<html><head><title>README</title></head><body>" > index.html
          if [ -f README.html ]; then
            cat README.html >> index.html
          else
            echo "<p>Error: README.html not found</p>" >> index.html
          fi
          echo "</body></html>" >> index.html

      # Upload HTML files as artifacts
      - name: Upload HTML files
        uses: actions/upload-artifact@v3
        with:
          name: HTML-files
          path: |
            README.html
            index.html
